// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence.Context;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250205021355_FixedSeedData")]
    partial class FixedSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Catalogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Catalogos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Created = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Descripcion = "Catalogo que identifica los roles de la aplicacion",
                            LastModified = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            LastModifiedBy = "System",
                            Nombre = "Roles"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Created = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Descripcion = "Catalogo que identifica las rutas de la aplicacion",
                            LastModified = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            LastModifiedBy = "System",
                            Nombre = "Rutas"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Created = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Descripcion = "Catalogo que identifica los formularios de la aplicacion",
                            LastModified = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            LastModifiedBy = "System",
                            Nombre = "Formularios"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
